name: RStore-Orbs
version: 1.4
main: me.ry4nn00b.orbs.Main
authors: [ Ry4nN00B ]
description: Plugin de Orbs, desenvolvido por [! Ry4nN00B#6006].
website: https://discord.gg/G4atpKWWNY
depend:
  - PowerNBT

commands:
  orbs:
    description: Comando para abrir o menu de orbs.
  giveorbs:
    description: Comando para ganhar orbs.
  removeorbs:
    description: Comando para remover orbs de um player.
  payorbs:
    description: Comando para enviar orbs entre players.
  orbsmsg:
    description: Comando usado para habilitar/desabilitar a mensagen do recebimento de orbs.
  boostorbs:
    description: Usado para dar um boost nas orbs do player.
  boostorbsall:
    description: Usado para dar boost a todos o servidor.
  orbsreload:
    description: Usado para recarregar as configs.

