#
#
#Variáveis(válidas apenas para o RStore-Orbs)
#   {orbs}, {player}, {target}, {tp}, {boost}
#
#A configuração já vem em um padrão balanceado,
#você pode alterar caso deseje.
#
#
Orbs:
  TP: 100
  Boost: 1.0
  TPLimit: "2B"
  OrbsLimit: 20000000
Mensagens:
  Prefix: "&b&lRStore-Orbs&f&l>> &f"
  NoPermission: "Você não possui permissão."
  OpenMenu: "Menu de orbs aberto."
  OffPlayer: "Escolha um jogador online."
  NoOrbs: "Você não possui orbs suficiente."
  RedeemOrbs: "Você resgatou suas orbs. &2+{tp}TP"
  GiveOrbsSender: "Foi adicionado &a{orbs} &forbs ao jogador &a{target}&f."
  GiveOrbsTarget: "Você recebeu &a{orbs} &forbs."
  PayOrbsPlayer: "Você enviou &a{orbs} &forbs para o player &a{target}&f."
  PayOrbsTarget: "O player &a{player} &fenviou &a{orbs} &forbs para você."
  RemoveOrbsSender: "Foi removido &a{orbs} &forbs do jogador &a{target}&f."
  RemoveOrbsTarget: "Você teve &a{orbs} &forbs removida."
  OrbsLimit: "Você atingiu o limite de orbs!"
  TPLimit: "Você atingiu o limite de TP!"
  BoostSender: "Foi adicionado um boost de &a{boost} &fpara o(a) jogador(a) &a{target}&f."
  BoostTarget: "Você recebeu um boost de orbs de &a{boost}&f."
  BoostTargetOff: "O seu boost de orbs acabou."
  BoostAllOn: "Acabou de ser ativado um boost &a{boost} &fpara todos do servidor."
  BoostAllOff: "O boost do servidor foi desativado."